package pl.edu.agh.eaiib.auctions.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-22T22:58:06.658+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://eaiib.agh.edu.pl/auctions/wsdl/", name = "GetAuctionsForClientSoap")
@XmlSeeAlso({pl.edu.agh.eaiib.auctions.xsd.ObjectFactory.class})
public interface GetAuctionsForClientSoap {

    /**
     * Method for searching auctions by client (all not finished + taken part)
     */
    @RequestWrapper(localName = "GetAuctionsForClient", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/", className = "pl.edu.agh.eaiib.auctions.xsd.GetAuctionsForClient")
    @WebMethod(operationName = "GetAuctionsForClient", action = "http://eaiib.agh.edu.pl/auction/GetAuctionsForClient")
    @ResponseWrapper(localName = "GetAuctionsForClientResponse", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/", className = "pl.edu.agh.eaiib.auctions.xsd.GetAuctionsForClientResponse")
    public void getAuctionsForClient(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ClientLogin", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/")
        javax.xml.ws.Holder<java.lang.String> clientLogin,
        @WebParam(name = "AuctionListFilter", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/")
        pl.edu.agh.eaiib.auctions.xsd.AuctionListFilterType auctionListFilter,
        @WebParam(mode = WebParam.Mode.OUT, name = "AuctionList", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/")
        javax.xml.ws.Holder<pl.edu.agh.eaiib.auctions.xsd.AuctionListType> auctionList
    );
}
