package pl.edu.agh.eaiib.auctions.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-15T01:04:42.674+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://eaiib.agh.edu.pl/auctions/wsdl/", name = "PutAuctionByManagerSoap")
@XmlSeeAlso({pl.edu.agh.eaiib.auctions.xsd.ObjectFactory.class})
public interface PutAuctionByManagerSoap {

    /**
     * Method for pushing data about auction by Auction Manager into the module
     */
    @RequestWrapper(localName = "PutAuctionByManager", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/", className = "pl.edu.agh.eaiib.auctions.xsd.PutAuctionByManager")
    @WebMethod(operationName = "PutAuctionByManager", action = "http://eaiib.agh.edu.pl/auction/PutAuctionByManager")
    @ResponseWrapper(localName = "PutAuctionByManagerResponse", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/", className = "pl.edu.agh.eaiib.auctions.xsd.PutAuctionByManagerResponse")
    public void putAuctionByManager(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Auction", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/")
        javax.xml.ws.Holder<pl.edu.agh.eaiib.auctions.xsd.AuctionType> auction,
        @WebParam(mode = WebParam.Mode.INOUT, name = "AMLogin", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/")
        javax.xml.ws.Holder<java.lang.String> amLogin,
        @WebParam(name = "AuctionManagerContactData", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/")
        pl.edu.agh.eaiib.auctions.xsd.AuctionManagerContactDataType auctionManagerContactData,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errors", targetNamespace = "http://eaiib.agh.edu.pl/auctions/xsd/")
        javax.xml.ws.Holder<java.lang.String> errors
    );
}
