package pl.edu.agh.useraccounts.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-21T09:54:04.581+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://service.useraccounts.agh.edu.pl/", name = "UsersParametersService")
@XmlSeeAlso({ObjectFactory.class})
public interface UsersParametersService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserParam", targetNamespace = "http://service.useraccounts.agh.edu.pl/", className = "pl.edu.agh.useraccounts.service.GetUserParam")
    @WebMethod
    @ResponseWrapper(localName = "getUserParamResponse", targetNamespace = "http://service.useraccounts.agh.edu.pl/", className = "pl.edu.agh.useraccounts.service.GetUserParamResponse")
    public java.lang.String getUserParam(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "paramKey", targetNamespace = "")
        java.lang.String paramKey
    ) throws UserException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setUserParam", targetNamespace = "http://service.useraccounts.agh.edu.pl/", className = "pl.edu.agh.useraccounts.service.SetUserParam")
    @WebMethod
    @ResponseWrapper(localName = "setUserParamResponse", targetNamespace = "http://service.useraccounts.agh.edu.pl/", className = "pl.edu.agh.useraccounts.service.SetUserParamResponse")
    public int setUserParam(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "paramKey", targetNamespace = "")
        java.lang.String paramKey,
        @WebParam(name = "paramValue", targetNamespace = "")
        java.lang.String paramValue
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserParams", targetNamespace = "http://service.useraccounts.agh.edu.pl/", className = "pl.edu.agh.useraccounts.service.GetUserParams")
    @WebMethod
    @ResponseWrapper(localName = "getUserParamsResponse", targetNamespace = "http://service.useraccounts.agh.edu.pl/", className = "pl.edu.agh.useraccounts.service.GetUserParamsResponse")
    public pl.edu.agh.useraccounts.service.Parameters getUserParams(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login
    ) throws UserException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLogs", targetNamespace = "http://service.useraccounts.agh.edu.pl/", className = "pl.edu.agh.useraccounts.service.GetLogs")
    @WebMethod
    @ResponseWrapper(localName = "getLogsResponse", targetNamespace = "http://service.useraccounts.agh.edu.pl/", className = "pl.edu.agh.useraccounts.service.GetLogsResponse")
    public java.util.List<java.lang.String> getLogs(
        @WebParam(name = "startTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    ) throws UserException_Exception;
}
