
package pl.edu.agh.useraccounts.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-08T00:45:40.413+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "UserException", targetNamespace = "http://service.useraccounts.agh.edu.pl/")
public class UserException_Exception extends Exception {
    
    private pl.edu.agh.useraccounts.service.UserException userException;

    public UserException_Exception() {
        super();
    }
    
    public UserException_Exception(String message) {
        super(message);
    }
    
    public UserException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserException_Exception(String message, pl.edu.agh.useraccounts.service.UserException userException) {
        super(message);
        this.userException = userException;
    }

    public UserException_Exception(String message, pl.edu.agh.useraccounts.service.UserException userException, Throwable cause) {
        super(message, cause);
        this.userException = userException;
    }

    public pl.edu.agh.useraccounts.service.UserException getFaultInfo() {
        return this.userException;
    }
}
